# Generated by Django 5.1.1 on 2024-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaeParticipantes",
            fields=[
                (
                    "codparticipante",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ap_materno", models.CharField(max_length=40)),
                ("ap_paterno", models.CharField(max_length=40)),
                ("correo", models.CharField(max_length=40)),
                ("qr_code", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "db_table": "mae_participantes",
                "managed": False,
            },
        ),
    ]
