# Generated by Django 5.1.1 on 2024-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministradorBloquecolaborador",
            fields=[
                ("idabc", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_bloquecolaborador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministradorBloques",
            fields=[
                ("idab", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_bloques",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministradorColaborador",
            fields=[
                ("idac", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_colaborador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministradorCongreso",
            fields=[
                ("idac", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_congreso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministradorPonencias",
            fields=[
                ("idap", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_ponencias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministradorPonentes",
            fields=[
                ("idapt", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "administrador_ponentes",
                "managed": False,
            },
        ),
    ]
